Added task 1
DmitryZusko/OOP pull request #1
Opened 2022-07-10 14:54 UTC by DmitryZusko

Added first task

2022-07-12 16:51 UTC, DmitryZusko commented on Task_1/ComplexNumber.cs
> +        public ComplexNumber()
But when constructor with arguments initialized, default constructor doesn't work without writing it in code.

2022-07-12 16:52 UTC, DmitryZusko commented on Task_1/ComplexNumber.cs
> +            //Should I use operation .ToList(), if Split returns array?
Ok

2022-07-14 18:34 UTC, DmitryZusko commented
In my last commit were next changes:
overwrote operators (suck as +, -, *);
overwrote method ToString();
implemented interfaces IComparable<>, IEquatable<>

So now I can use ComplexNumber class with custom Generic classes

2022-07-23 15:03 UTC, mornado requested changes

2022-07-23 15:03 UTC, mornado commented on Task_1/ComplexNumber.cs
> +            var complex3 = new ComplexNumber(complex1.Real - complex2.Real, complex1.Imaginary - complex2.Imaginary);
Useless line.)

2022-07-23 15:03 UTC, mornado commented on Task_1/ComplexNumber.cs
> +            complex3.Real = Math.Round(complex1.Real * complex2.Real - complex1.Imaginary * complex2.Imaginary, PRECISION);
Can be processed during initialisation of complex3 variable.

2022-07-23 15:27 UTC, mornado approved these changes

2022-07-23 15:54 UTC, merged